/// Embedded NOTICES file generated by `make notices` (cargo about).
/// Re-run `make notices` after any `cargo update` to keep this current.
static NOTICES: &str = include_str!("../../NOTICES");

pub fn run() -> anyhow::Result<()> {
    println!("{NOTICES}");
    Ok(())
}
