import SwiftUI

// MARK: - Model

/// One open-source dependency entry, decoded from Acknowledgments.json
/// (generated by scripts/generate-acknowledgments.py).
struct Acknowledgment: Identifiable, Decodable {
    let id = UUID()
    let name: String
    let version: String
    let license: String
    let url: String
    let authors: String
    let licenseText: String

    // JSON keys match the snake_case / camelCase produced by the generator
    private enum CodingKeys: String, CodingKey {
        case name, version, license, url, authors
        case licenseText
    }
}

// MARK: - Bundle loader

extension Acknowledgment {
    /// All entries decoded from the bundled Acknowledgments.json.
    /// Returns an empty array (and logs a warning) if the file is missing or malformed.
    static let all: [Acknowledgment] = {
        guard let url = Bundle.main.url(forResource: "Acknowledgments", withExtension: "json") else {
            assertionFailure("Acknowledgments.json not found in app bundle — run `make acknowledgments`")
            return []
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode([Acknowledgment].self, from: data)
        } catch {
            assertionFailure("Failed to decode Acknowledgments.json: \(error)")
            return []
        }
    }()
}

// MARK: - View

struct AcknowledgmentsView: View {
    @State private var selection: Acknowledgment.ID?

    private var selectedItem: Acknowledgment? {
        Acknowledgment.all.first { $0.id == selection }
    }

    var body: some View {
        NavigationSplitView {
            List(Acknowledgment.all, selection: $selection) { item in
                VStack(alignment: .leading, spacing: 2) {
                    HStack {
                        Text(item.name)
                            .fontWeight(.medium)
                        Spacer()
                        if !item.version.isEmpty {
                            Text(item.version)
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                    }
                    Text(item.license)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                .padding(.vertical, 2)
            }
            .navigationSplitViewColumnWidth(min: 180, ideal: 220)
        } detail: {
            if let item = selectedItem {
                LicenseDetailView(item: item)
            } else {
                Text("Select a library")
                    .foregroundStyle(.tertiary)
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            }
        }
        .onAppear {
            selection = Acknowledgment.all.first?.id
        }
    }
}

// MARK: - Detail

private struct LicenseDetailView: View {
    let item: Acknowledgment

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                // Header
                VStack(alignment: .leading, spacing: 4) {
                    HStack(alignment: .firstTextBaseline, spacing: 8) {
                        Text(item.name)
                            .font(.title2)
                            .fontWeight(.semibold)
                        if !item.version.isEmpty {
                            Text(item.version)
                                .font(.callout)
                                .foregroundStyle(.secondary)
                        }
                    }
                    if !item.authors.isEmpty {
                        Text(item.authors)
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                    }
                    if let destination = URL(string: item.url) {
                        Link(item.url, destination: destination)
                            .font(.subheadline)
                    }
                }

                Divider()

                // License badge
                Text(item.license)
                    .font(.caption)
                    .fontWeight(.medium)
                    .padding(.horizontal, 8)
                    .padding(.vertical, 3)
                    .background(.quaternary, in: RoundedRectangle(cornerRadius: 4))
                    .foregroundStyle(.secondary)

                // Full license text
                Text(item.licenseText)
                    .font(.system(.caption, design: .monospaced))
                    .foregroundStyle(.secondary)
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
            .padding(20)
        }
        .navigationSplitViewColumnWidth(min: 360, ideal: 480)
    }
}

#Preview {
    AcknowledgmentsView()
        .frame(width: 700, height: 480)
}
